In [ ]:
import pandas as pd

df = pd.read_excel("ngoerah vpk des 12-12-2025.xlsx", header=2)
df.head()

## Load Dataset

#### Aspek Koding

In [32]:
import pandas as pd

# expand the column width to see the full sentences
pd.set_option('display.max_colwidth', None)

# Sheet ID
sheet_id = "1xsnYzfj152gI2N9gIDvAN7GncW6rvjRb"
# GID 
gid = "1838314148"

# Format for CSV export
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

# Read DataFrame
df_aspek_koding = pd.read_csv(url)

df_aspek_koding.head()

,No,Domain,Kategori ICD,Diagnosis,Prosedur,Aspek Koding,Perhatian Khusus,Keterangan
0,1,Diagnosis,Penyakit-Penyakit Infeksi dan Parasit Tertentu,Typhoid Fever (A01) / Infection due to Salmonella typhi A01.0,-,"Typhoid fever \nInfection due to Salmonella typhi A01.0\nParatyphoid fever A A01.1\nParatyphoid fever B A01.2\nParatyphoid fever C A01.3\nParatyphoid fever, unspecified A01.4 - Infection due to Salmonella paratyphi NOS",Penegakan diagnosis sesuai dengan Keputusan Menteri Kesehatan Ri Nomor HK 02.02/MENKES/514/2015. Perhatikan Dagger dan Asterisk,BA Kesepakatan Bersama Tahun 2018
1,2,Diagnosis,Penyakit-Penyakit Infeksi dan Parasit Tertentu,Typhoid pada kehamilan (dirawat oleh dokter spesialis dalam),-,"Jika tidak ada diagnosis lainnya, maka pengkodaan untuk kasus tifoid pada kehamilan menggunakan kode 098 8 sebagai diagnosis utama dan kode A01.0 sebagai diagnosis sekunder","Sesuai PMK No.76 Tahun 2016. Jika dalam ICD-10 terdapat catatan seperti Lise additional code, if desired, to identify specified condition, maka kode tersebut dapat digunakan sesuai dengan kondisi pasien.",BA Kesepakatan Bersama Tahun 2018
2,3,Diagnosis,Penyakit-Penyakit Infeksi dan Parasit Tertentu,Penggunaan kode kombinasi untuk Typhoid fever (A01) dengan Dianhoea and gastroententis of presumed infectious engin menjadi Salmonella enteritis,-,"Sesuai dengan instruksi excludes pada volume I sub bab other gastroententis and colitis of infectious and unspecified onigin fever (A09) yang menyatakan gastroententis and colitis due to bacterial, protozoal, viral and other specified infectious agents mengarah pada kode spesifik sesuai dengan organismenya (A00-A08) Sehingga kode A09 seharusnya tidak dikoding lagi apabila sudah ada typhoid fever (A01.0) yang tegak secara medis. Tidak ada instruksi khusus untuk menggabungkan antara A01.0 dengan A09 menjadi salmonella, enteritis (A02.0) baik dari volume 1 maupun III",-,BA Kesepakatan Bersama Tahun 2018
3,4,Diagnosis,Penyakit-Penyakit Infeksi dan Parasit Tertentu,Diare (409),-,"Diare noninfeksius menggunakan kode : K52.9\nDiare noninfeksius pada neonatus menggunakan kode: P78.3.\nMohon diperhatikan pada ICD-10 Revisi Tahun 2010 terkait koding A09.- A09.0 dan A09.9 digunakan untuk diare yang penyebabnya tidak diketahui penyebabnya. Jika penyebab diare sudah diketahui maka gunakan kode spesifik. Jika disebabkan oleh bakteri, protozoa, virus, dan organisme spesifik lainnya : A00-A08.\nICD 10 2010 Volume 1\nA09 Other gastroenteritis and colitis of infectious and unspecified origin\nExcludes: due to bacterial, protozoal, viral and other specified infectious agents ( A00-A08 )\nNoninfective (see noninfectious) diarrhoea ( K52.9 ) neonatal ( P78.3 )","Diare yang merupakan gejala/bagian dari suatu infeksi (contoh: Thypoid) tidak perlu dikoding terpisah dari penyakit utamanya sebagai sumber infeksi atau tidak dijadikan DU.\nContoh : GE akibat infeksi Entamoeba Histolytica disebut disentri dikoding dengan menggunakan kode A06.0\nSesuai ICD 10 2010 Volume 1, diagnosa diarrhoea and gastroenteritis of presumed infectious origin (A09) dengan Typhoid fever (A01.0) dikode kombinasi dengan Typhoid fever (A01.0)",BA Kesepakatan Bersama Tahun 2018
4,5,Diagnosis,Penyakit-Penyakit Infeksi dan Parasit Tertentu,TB dengan Pneumonia/Bronkhopneumonia menggunakan kode gabung yaitu A15/A15,-,Secara kaidah ICD 10 terdapat kode A16 2 Tuberculosis of lung dengan penjelasan bahwa kondisi Tuberculous pneumonia sudah termasuk (include) dalam kode A16.2,-,BA Kesepakatan Bersama Tahun 2018

In [33]:
df_aspek_koding.isnull().sum()

No                  0
Domain              0
Kategori ICD        0
Diagnosis           0
Prosedur            0
Aspek Koding        0
Perhatian Khusus    5
Keterangan          0
dtype: int64

In [34]:
df_aspek_koding.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   No                210 non-null    int64
 1   Domain            210 non-null    object
 2   Kategori ICD      210 non-null    object
 3   Diagnosis         210 non-null    object
 4   Prosedur          210 non-null    object
 5   Aspek Koding      210 non-null    object
 6   Perhatian Khusus  205 non-null    object
 7   Keterangan        210 non-null    object
dtypes: int64(1), object(7)
memory usage: 13.3+ KB

### Aspek Medis

In [35]:
import pandas as pd

# expand the column width to see the full sentences
pd.set_option('display.max_colwidth', None)

# GID 
gid = "953771826"

# Format for CSV export
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

# Read DataFrame
df_aspek_medis = pd.read_csv(url)

df_aspek_medis.head()

,No,Diagnosis,Prosedur,Aspek Medis,Perhatian Khusus,Keterangan
0,1,Diagnosis sekunder Shock Kardiogenik pada kasus meninggal,-,"Kondisi Syok Kardiogenik dapat menjadi diagnosis sekunder terutama pada pasien penyakit jantung dengan bukti tertulisnya kriteria klinis dalam rekam medis berupa :\n1. Penurunan Tekanan Darah\na. TD < 90 mmHg tanpa inotropik, atau\nb. TD < 80 mmHg dengan inotropik\n2. Penurunan Ejection Fraction (EF < 50%)",Tidak boleh dikoding bila tidak tegak secara medis dan tidak ada resource khusus.,BA Kesepakatan Bersama Tahun 2018
1,2,-,USG pada Kehamilan (88.76 / 88.79),"Dalam kondisi kehamilan normal, prosedur USG dilakukan sebanyak 3 kali (1 kali tiap trimester). Pada kehamilan dengan indikasi medis lainnya membutuhkan lebih banyak prosedur USG.",-,BA Kesepakatan Bersama Tahun 2018
2,3,Pneumonia / Bronkopneumonia,-,"Pneumonia dapat didiagnosis sesuai dengan KMK RI No. HK. 02.02/MENKES/514/2015 yaitu jika pada foto toraks terdapat infiltrat baru atau infiltrat progresif ditambah dengan 2 atau lebih gejala dibawah ini :\n1. Batuk-batuk bertambah\n2. Perubahan karakteristik dahak / purulen\n3. Suhu tubuh > 38°C (aksila) / riwayat demam\n4. Pemeriksaan fisik : ditemukan tanda-tanda konsolidasi, suara napas bronkial dan ronki\n5. Leukosit > 10.000 atau < 4500",-,BA Kesepakatan Bersama Tahun 2018
3,4,TB Paru (A15),-,"TB Paru dapat didiagnosis dengan melampirkan hasil pemeriksaan penunjang positif (imaging, BTA) dan mendapatkan tatalaksana khusus berupa Obat Anti Tuberkulosis (OAT). Jika hasil BTA negatif menggunakan kode A16.-",-,BA Kesepakatan Bersama Tahun 2018
4,5,Hiponatremi,-,"Kondisi dimana kadar natrium lebih rendah dari nilai normal (Na < 135 mEq/L), maka kondisi tersebut tetap dikatakan sebagai hiponatremia, dan dapat digunakan sebagai diagnosa sekunder apabila ada tatalaksana/terapi diberikan.\nPada anak natrium dibawah 130 dan/atau terdapat kondisi klinis kejang atau penurunan kesadaran atau dehidrasi berat. Untuk dengan penyerta penyakit jantung dibawah 135.",-,BA Kesepakatan Bersama Tahun 2018

In [36]:
df_aspek_medis.isnull().sum()

No                  0
Diagnosis           0
Prosedur            0
Aspek Medis         0
Perhatian Khusus    0
Keterangan          0
dtype: int64

In [37]:
df_aspek_medis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   No                69 non-null     int64
 1   Diagnosis         69 non-null     object
 2   Prosedur          69 non-null     object
 3   Aspek Medis       69 non-null     object
 4   Perhatian Khusus  69 non-null     object
 5   Keterangan        69 non-null     object
dtypes: int64(1), object(5)
memory usage: 3.4+ KB

### Aspek Administrasi

In [38]:
import pandas as pd

# expand the column width to see the full sentences
pd.set_option('display.max_colwidth', None)

# GID 
gid = "548818279"

# Format for CSV export
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"

# Read DataFrame
df_aspek_administrasi = pd.read_csv(url)

df_aspek_administrasi.head()

,No,Diagnosis,Prosedur,Perihal Administrasi,Solusi Administrasi,Perhatian Khusus,Keterangan
0,1,"Kasus Haemofilia: harus ada rujukan balik (protokol terapi) dari PPK 3 dan surat rujukan menyusul, tidak bisa diklaimkan sebagai kasus Haemofilia",-,-,"Sesuai dengan Keputusan Menteri Kesehatan Republik Indonesia No. HK. 02.02/MENKES/523/2015 bahwa Peresepan Produk Darah Faktor VIIa (rekombinan), hanya boleh diberikan oleh hematolog dewasa atau hematolog anak.\nYang diterima adalah kasus dengan protokol terapi yang sudah ada namun tidak dibawa. Untuk yang belum ada protokol terapi dan tidak ada penegakan diagnosis dari PPK 3 sebelumnya, tidak diberikan penjaminan.",-,BA Kesepakatan Bersama Tahun 2018
1,2,Penggunaan kode Z09.8 pada RS Khusus Kanker ditagihkan dengan tarif RS Khusus,-,-,Pasien kontrol diluar diagnosa kekhususan (diluar fokus treatment) pada RS khusus diklaimkan satu tingkat kelas tarif dibawahnya. Kode Z09.8 pada diagnosa kekhususan : di klaimkan sesuai dengan kelas RS khusus. Kode Z09.8 pada diagnosa non kekhususan : diklaimkan satu tingkat kelas tarif dibawahnya.,-,BA Kesepakatan Bersama Tahun 2018
2,3,-,-,Apakah operasi eviserasi dan enukleasi dengan anestesi umum disarankan dirujuk ke rumah sakit tipe B atau tipe A?,"Sesuai dengan Peraturan Menteri Kesehatan No. 28 Tahun 2014 yaitu : Pelayanan kesehatan dilaksanakan secara berjenjang dimulai dari pelayanan kesehatan tingkat pertama. Pelayanan kesehatan tingkat kedua hanya dapat diberikan atas rujukan dari pelayanan kesehatan tingkat pertama. Pelayanan kesehatan tingkat ketiga hanya dapat diberikan atas rujukan dari pelayanan kesehatan tingkat kedua atau tingkat pertama, kecuali pada keadaan gawat darurat, kekhususan permasalahan kesehatan pasien, pertimbangan geografis, dan pertimbangan ketersediaan fasilitas. Kriteria rujukan sesuai dengan indikasi medis, kompetensi dokter, dan sarana prasarana yang tersedia. Selama mempunyai fasilitas dan memilki kompetensi yang sesuai, tidak perlu di rujuk.",-,BA Kesepakatan Bersama Tahun 2018
3,4,-,-,"Prosedur kombinasi (contoh: SICS/Fakoemulsifikasi + IOL + trabekulektomi), perhitungan klaim dihitung satu atau dua prosedur?","Tindakan/prosedur yang telah dilaksanakan ditulis dan dikode sesuai kaidah koding ICD-9-CM Tahun 2010 secara lengkap, jelas, dan spesifik.",-,BA Kesepakatan Bersama Tahun 2018
4,5,-,-,"Pada rawat jalan, apakah pemeriksaan seperti refraksi kacamata, slit lamp, funduskopi, tonometer mempunyai jasa pelayanan/klaim tersendiri?",Sesuai dengan Peraturan Menteri Kesehatan No. 28 Tahun 2014 bahwa untuk FKRTL BPJS Kesehatan akan membayar dengan sistem paket INA CBG's dan di luar paket INA CBGs. Pembayaran pelayanan kesehatan dengan menggunakan sistem INA CBGs terhadap FKRTL berdasarkan pada pengajuan klaim dari FKRTL baik untuk pelayanan rawat jalan maupun untuk pelayanan rawat inap.,-,BA Kesepakatan Bersama Tahun 2018

In [39]:
df_aspek_administrasi.isnull().sum()

No                      0
Diagnosis               0
Prosedur                0
Perihal Administrasi    1
Solusi Administrasi     0
Perhatian Khusus        0
Keterangan              0
dtype: int64

In [40]:
df_aspek_administrasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   No                    11 non-null     int64
 1   Diagnosis             11 non-null     object
 2   Prosedur              11 non-null     object
 3   Perihal Administrasi  10 non-null     object
 4   Solusi Administrasi   11 non-null     object
 5   Perhatian Khusus      11 non-null     object
 6   Keterangan            11 non-null     object
dtypes: int64(1), object(6)
memory usage: 748.0+ bytes

## Data Extraction to the MD

In [41]:
import os
import re
import unicodedata

def sanitize_filename(name, max_length=120):
    """
    Convert any string into a filesystem-safe filename.
    """

    # Normalize unicode (avoid weird hidden characters)
    name = unicodedata.normalize("NFKD", str(name))

    # Remove control characters
    name = re.sub(r'[\x00-\x1f\x7f]', '', name)

    # Remove invalid Windows characters
    name = re.sub(r'[\\/*?:"<>|]', '', name)

    # Remove leading/trailing whitespace
    name = name.strip()

    # Remove trailing dots (Windows restriction)
    name = name.rstrip(".")

    # Prevent empty filename
    if not name:
        name = "unknown"

    # Prevent reserved Windows names
    reserved = {
        "CON","PRN","AUX","NUL",
        "COM1","COM2","COM3","COM4","COM5","COM6","COM7","COM8","COM9",
        "LPT1","LPT2","LPT3","LPT4","LPT5","LPT6","LPT7","LPT8","LPT9"
    }

    if name.upper() in reserved:
        name = f"{name}_file"

    # Limit length (prevent path > 255)
    name = name[:max_length]

    return name

In [42]:
import os
import re
				
# Extraction Aspek Koding Documents
def extraction_aspek_koding(data):
    # Make folder if doesn't exists
    output_dir = "Knowledge"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Original logic (unchanged)
    raw_file_name = data["Prosedur"] if data["Diagnosis"] == "-" else data["Diagnosis"]

    # Sanitize filename
    safe_name = sanitize_filename(raw_file_name)

    file_path = os.path.join(output_dir, f"{safe_name}.md")

    # Prevent accidental overwrite
    counter = 1
    base_path = file_path
    while os.path.exists(file_path):
        file_path = os.path.join(output_dir, f"{safe_name}_{counter}.md")
        counter += 1

    # Document Template
    document = f"""

**DOMAIN:**
{data['Domain']}

**KATEGORI ICD:**
{data['Kategori ICD']}

**DIAGNOSIS:**
{data["Diagnosis"]}

**PROSEDUR:**
{data["Prosedur"]}

**ASPEK KODING:**
{data["Aspek Koding"]}

**PERHATIAN KHUSUS:**
{data["Perhatian Khusus"]}
"""

    # Read File
    try:
        with open(file_path, "w", encoding="utf-8") as file:
            file.write(document)
        return "success"
    except Exception as error:
        print("Failed:", file_path)
        print("Error:", error)
        return "failed"

	
# Extraction Aspek Medis Documents
def extraction_aspek_medis(data):
    # Make folder if doesn't exists
    output_dir = "Knowledge"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Original logic (unchanged)
    raw_file_name = data["Prosedur"] if data["Diagnosis"] == "-" else data["Diagnosis"]

    # Sanitize filename
    safe_name = sanitize_filename(raw_file_name)

    file_path = os.path.join(output_dir, f"{safe_name}.md")

    # Prevent accidental overwrite
    counter = 1
    base_path = file_path
    while os.path.exists(file_path):
        file_path = os.path.join(output_dir, f"{safe_name}_{counter}.md")
        counter += 1

    # Document Template
    document = f"""


**DIAGNOSIS:**
{data["Diagnosis"]}

**PROSEDUR:**
{data["Prosedur"]}

**ASPEK MEDIS:**
{data["Aspek Medis"]}

**PERHATIAN KHUSUS:**
{data["Perhatian Khusus"]}
"""

    # Read File
    try:
        with open(file_path, "w", encoding="utf-8") as file:
            file.write(document)
        return "success"
    except Exception as error:
        print("Failed:", file_path)
        print("Error:", error)
        return "failed"


# Extraction Aspek Administrasi Documents
def extraction_aspek_administrasi(data):
    
    # Make folder if doesn't exists
    output_dir = "Knowledge"
    os.makedirs(output_dir, exist_ok=True)

    # Original logic (unchanged)
    if data["Diagnosis"] == "-":
        raw_file_name = data["Prosedur"]
    elif data["Prosedur"] == "-":
        raw_file_name = data["Perihal Administrasi"]
    else:
        raw_file_name = data["Diagnosis"]

    # Use the SAME sanitizer
    safe_name = sanitize_filename(raw_file_name)

    file_path = os.path.join(output_dir, f"{safe_name}.md")

    # Prevent overwrite
    counter = 1
    while os.path.exists(file_path):
        file_path = os.path.join(output_dir, f"{safe_name}_{counter}.md")
        counter += 1

    document = f"""

**DIAGNOSIS:**
{data["Diagnosis"]}

**PROSEDUR:**
{data["Prosedur"]}

**PERIHAL ADMINISTRASI:**
{data["Perihal Administrasi"]}

**SOLUSI ADMINISTRASI:**
{data["Solusi Administrasi"]}

**PERHATIAN KHUSUS:**
{data["Perhatian Khusus"]}
"""

    try:
        with open(file_path, "w", encoding="utf-8") as file:
            file.write(document)
        return "success"
    except Exception as error:
        print("Failed:", file_path)
        print("Error:", error)
        return "failed"

In [43]:
# Apply Extraction Aspek Koding
df_aspek_koding.apply(extraction_aspek_koding, axis=1)

0      success
1      success
2      success
3      success
4      success
        ...
205    success
206    success
207    success
208    success
209    success
Length: 210, dtype: object

In [44]:
# Apply Extraction Aspek Medis
df_aspek_medis.apply(extraction_aspek_medis, axis=1)

0     success
1     success
2     success
3     success
4     success
       ...
64    success
65    success
66    success
67    success
68    success
Length: 69, dtype: object

In [45]:
# Apply Extraction Aspek Administrasi
df_aspek_administrasi.apply(extraction_aspek_administrasi, axis=1)

0     success
1     success
2     success
3     success
4     success
5     success
6     success
7     success
8     success
9     success
10    success
dtype: object

In [ ]:
# def extract_coding_aspect(data):
#     output_dir = "Knowledge"
#     os.makedirs(output_dir, exist_ok=True)

#     # Original logic (unchanged)
#     raw_file_name = data["Prosedur"] if data["Diagnosis"] == "-" else data["Diagnosis"]

#     # Sanitize filename
#     safe_name = sanitize_filename(raw_file_name)

#     file_path = os.path.join(output_dir, f"{safe_name}.md")

#     # Prevent accidental overwrite
#     counter = 1
#     base_path = file_path
#     while os.path.exists(file_path):
#         file_path = os.path.join(output_dir, f"{safe_name}_{counter}.md")
#         counter += 1

#     document_content = f"""
# **DOMAIN:**
# {data['Domain']}

# **ICD CATEGORY:**
# {data['Kategori ICD']}

# **DIAGNOSIS:**
# {data["Diagnosis"]}

# **PROCEDURE:**
# {data["Prosedur"]}

# **CODING ASPECT:**
# {data["Aspek Koding"]}

# **SPECIAL ATTENTION:**
# {data["Perhatian Khusus"]}

# **NOTES:**
# {data["Keterangan"]}
# """

#     try:
#         with open(file_path, "w", encoding="utf-8") as file:
#             file.write(document_content)
#         return "success"
#     except Exception as error:
#         print("Failed:", file_path)
#         print("Error:", error)
#         return "failed"

In [ ]:
# def extract_medical_aspect(data):
#     output_dir = "Knowledge"
#     os.makedirs(output_dir, exist_ok=True)

#     # Original logic (unchanged)
#     raw_file_name = data["Prosedur"] if data["Diagnosis"] == "-" else data["Diagnosis"]

#     # Sanitize filename
#     safe_name = sanitize_filename(raw_file_name)

#     file_path = os.path.join(output_dir, f"{safe_name}.md")

#     # Prevent accidental overwrite
#     counter = 1
#     base_path = file_path
#     while os.path.exists(file_path):
#         file_path = os.path.join(output_dir, f"{safe_name}_{counter}.md")
#         counter += 1


#     document_content = f"""
# **DIAGNOSIS:**
# {data["Diagnosis"]}

# **PROSEDUR:**
# {data["Prosedur"]}

# **ASPEK MEDIS:**
# {data["Aspek Medis"]}

# **PERHATIAN KHUSUS:**
# {data["Perhatian Khusus"]}

# **KETERANGAN:**
# {data["Keterangan"]}
# """

#     try:
#         with open(file_path, "w", encoding="utf-8") as file:
#             file.write(document_content)
#         return "success"
#     except Exception as error:
#         print("Failed:", file_path)
#         print("Error:", error)
#         return "failed"

In [ ]:
# # Apply All Extraction 
# df_aspek_koding.apply(extract_coding_aspect, axis=1)
# # df_aspek_medis.apply(extraction_aspek_medis, axis=1)
# # df_aspek_administrasi.apply(extraction_aspek_administrasi, axis=1)

0      success
1      success
2      success
3      success
4      success
        ...
205    success
206    success
207    success
208    success
209    success
Length: 210, dtype: object

In [ ]:
# import os
# total_files = sum(len(files) for _, _, files in os.walk('./Knowledge'))
# print(total_files)

208

In [1]:
import requests
import json
import re

url = "https://ai-api.paperlesshospital.id/api/chat"

payload = {
    "model": "qwen2.5:7b-instruct",
    "stream": False,
    "messages": [
        {
            "role": "system",
            "content": (
                "Anda adalah validator klaim BPJS. "
                "WAJIB output JSON valid saja. "
                "Tidak boleh ada teks di luar JSON. "
                "Semua field harus selalu ada walaupun kosong. "
                "Jika tidak ada data isi dengan []."
            )
        },
        {
            "role": "user",
            "content": """### ATURAN ###
Sepsis harus memenuhi:
1. Minimal 2 kriteria SIRS (Suhu >38.5 atau <36, Nadi >90, RR >20)
2. Harus ada bukti laboratorium
3. Harus diberikan antibiotik IV

### KASUS ###
Diagnosis: Septikemia
Suhu: 37.8
Nadi: 88
RR: 18
Leukosit: normal
Kultur darah: tidak ada
Antibiotik: oral

Lakukan validasi sesuai schema berikut:
{
  "complete": [],
  "incomplete": {
    "analisa_aturan_bak": [],
    "analisa_aturan_klinis": [],
    "analisa_permenkes": [],
    "analisa_aturan_coding_medis": []
  },
  "improvement_suggestions": {
    "analisa_aturan_bak": [],
    "analisa_aturan_klinis": [],
    "analisa_permenkes": [],
    "analisa_aturan_coding_medis": []
  }
}
"""
        }
    ],
    "options": {
        "temperature": 0.1
    }
}

headers = {
    "Content-Type": "application/json"
}

response = requests.post(url, headers=headers, json=payload)

# Cek status
print("Status Code:", response.status_code)

# Print raw response
print("Raw Response:")
print(response.text)

# Jika ingin parse JSON
try:
    result = response.json()
    print("\nParsed JSON:")
    print(json.dumps(result, indent=2))
except Exception as e:
    print("Gagal parse JSON:", e)

Status Code: 200
Raw Response:
{"model":"qwen2.5:7b-instruct","created_at":"2026-03-05T00:30:16.845252415Z","message":{"role":"assistant","content":"```json\n{\n  \"complete\": [],\n  \"incomplete\": {\n    \"analisa_aturan_bak\": [\n      \"Tidak memenuhi kriteria SIRS (tidak mencapai minimal 2 kriteria)\"\n    ],\n    \"analisa_aturan_klinis\": [\n      \"Tidak memenuhi kriteria SIRS (tidak mencapai minimal 2 kriteria)\",\n      \"Tidak ada bukti laboratorium\",\n      \"Antibiotik diberikan dalam bentuk oral, tidak IV\"\n    ],\n    \"analisa_permenkes\": [],\n    \"analisa_aturan_coding_medis\": []\n  },\n  \"improvement_suggestions\": {\n    \"analisa_aturan_bak\": [\n      \"Perlu penambahan kriteria SIRS lainnya untuk memenuhi minimal 2 kriteria\",\n      \"Periksa ulang laboratorium untuk menemukan bukti laboratorium yang relevan\"\n    ],\n    \"analisa_aturan_klinis\": [\n      \"Perbaiki dengan memberikan antibiotik IV\",\n      \"Tambahan kriteria SIRS lainnya untuk memenuhi minimal 2 kriteria\",\n      \"Periksa ulang laboratorium untuk menemukan bukti laboratorium yang relevan\"\n    ],\n    \"analisa_permenkes\": [],\n    \"analisa_aturan_coding_medis\": []\n  }\n}\n```"},"done":true,"done_reason":"stop","total_duration":2897990140,"load_duration":1259247475,"prompt_eval_count":315,"prompt_eval_duration":36589435,"eval_count":303,"eval_duration":1399057547}

Parsed JSON:
{
  "model": "qwen2.5:7b-instruct",
  "created_at": "2026-03-05T00:30:16.845252415Z",
  "message": {
    "role": "assistant",
    "content": "```json\n{\n  \"complete\": [],\n  \"incomplete\": {\n    \"analisa_aturan_bak\": [\n      \"Tidak memenuhi kriteria SIRS (tidak mencapai minimal 2 kriteria)\"\n    ],\n    \"analisa_aturan_klinis\": [\n      \"Tidak memenuhi kriteria SIRS (tidak mencapai minimal 2 kriteria)\",\n      \"Tidak ada bukti laboratorium\",\n      \"Antibiotik diberikan dalam bentuk oral, tidak IV\"\n    ],\n    \"analisa_permenkes\": [],\n    \"analisa_aturan_coding_medis\": []\n  },\n  \"improvement_suggestions\": {\n    \"analisa_aturan_bak\": [\n      \"Perlu penambahan kriteria SIRS lainnya untuk memenuhi minimal 2 kriteria\",\n      \"Periksa ulang laboratorium untuk menemukan bukti laboratorium yang relevan\"\n    ],\n    \"analisa_aturan_klinis\": [\n      \"Perbaiki dengan memberikan antibiotik IV\",\n      \"Tambahan kriteria SIRS lainnya untuk memenuhi minimal 2 kriteria\",\n      \"Periksa ulang laboratorium untuk menemukan bukti laboratorium yang relevan\"\n    ],\n    \"analisa_permenkes\": [],\n    \"analisa_aturan_coding_medis\": []\n  }\n}\n```"
  },
  "done": true,
  "done_reason": "stop",
  "total_duration": 2897990140,
  "load_duration": 1259247475,
  "prompt_eval_count": 315,
  "prompt_eval_duration": 36589435,
  "eval_count": 303,
  "eval_duration": 1399057547
}

In [2]:
import requests
import json
import re

response = requests.post(url, headers=headers, json=payload)
result = response.json()

# Ambil content saja
content = result["message"]["content"]

# Bersihkan markdown ```json ```
cleaned = re.sub(r"```json|```", "", content).strip()

# Parse ulang jadi JSON object
parsed_json = json.loads(cleaned)

print("Final Parsed JSON:")
print(json.dumps(parsed_json, indent=2))

Final Parsed JSON:
{
  "complete": [],
  "incomplete": {
    "analisa_aturan_bak": [
      "Tidak memenuhi kriteria SIRS (tidak ada suhu >38.5 atau <36, nadi >90)"
    ],
    "analisa_aturan_klinis": [
      "Tidak memenuhi kriteria SIRS (tidak ada suhu >38.5 atau <36, nadi >90)",
      "Tidak ada bukti laboratorium (kultur darah tidak ada)"
    ],
    "analisa_permenkes": [
      "Tidak memenuhi kriteria SIRS (tidak ada suhu >38.5 atau <36, nadi >90)",
      "Tidak ada bukti laboratorium (kultur darah tidak ada)"
    ],
    "analisa_aturan_coding_medis": [
      "Tidak memenuhi kriteria SIRS (tidak ada suhu >38.5 atau <36, nadi >90)",
      "Tidak ada bukti laboratorium (kultur darah tidak ada)",
      "Antibiotik diberikan oral, bukan IV"
    ]
  },
  "improvement_suggestions": {
    "analisa_aturan_bak": [
      "Perlu penambahan suhu >38.5 atau <36 dan nadi >90",
      "Perlu adanya bukti laboratorium (kultur darah)",
      "Perlu pemberian antibiotik IV"
    ],
    "analisa_aturan_klinis": [
      "Perlu penambahan suhu >38.5 atau <36 dan nadi >90",
      "Perlu adanya bukti laboratorium (kultur darah)",
      "Perlu pemberian antibiotik IV"
    ],
    "analisa_permenkes": [
      "Perlu penambahan suhu >38.5 atau <36 dan nadi >90",
      "Perlu adanya bukti laboratorium (kultur darah)",
      "Perlu pemberian antibiotik IV"
    ],
    "analisa_aturan_coding_medis": [
      "Perlu penambahan suhu >38.5 atau <36 dan nadi >90",
      "Perlu adanya bukti laboratorium (kultur darah)",
      "Perlu pemberian antibiotik IV"
    ]
  }
}

In [8]:
import requests
import json

url = "https://ai-api.paperlesshospital.id/api/chat"

schema = {
    "type": "object",
    "properties": {
        "complete": {
            "type": "array",
            "items": {"type": "string"}
        },
        "incomplete": {
            "type": "object",
            "properties": {
                "analisa_aturan_bak": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_klinis": {"type": "array", "items": {"type": "string"}},
                "analisa_permenkes": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_coding_medis": {"type": "array", "items": {"type": "string"}}
            },
            "required": [
                "analisa_aturan_bak",
                "analisa_aturan_klinis",
                "analisa_permenkes",
                "analisa_aturan_coding_medis"
            ]
        },
        "improvement_suggestions": {
            "type": "object",
            "properties": {
                "analisa_aturan_bak": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_klinis": {"type": "array", "items": {"type": "string"}},
                "analisa_permenkes": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_coding_medis": {"type": "array", "items": {"type": "string"}}
            },
            "required": [
                "analisa_aturan_bak",
                "analisa_aturan_klinis",
                "analisa_permenkes",
                "analisa_aturan_coding_medis"
            ]
        }
    },
    "required": ["complete", "incomplete", "improvement_suggestions"]
}

context_rules = """
### ATURAN SEPSIS ###
1. Minimal 2 kriteria SIRS:
   - Suhu >38.5 atau <36
   - Nadi >90
   - RR >20
2. Harus ada bukti laboratorium (Leukosit abnormal atau kultur positif)
3. Harus diberikan antibiotik IV
"""

new_document = """
### DOKUMEN KLAIM BARU ###
Diagnosis: Septikemia
Suhu: 39.1
Nadi: 110
RR: 24
Leukosit: 18.000
Kultur darah: positif
Antibiotik: IV
"""

payload = {
    "model": "paperless_Q25I7B:latest",
    "stream": False,
    "messages": [
        {
            "role": "system",
            "content": "Anda adalah validator klaim BPJS. Analisa hanya berdasarkan context aturan yang diberikan."
        },
        {
            "role": "user",
            "content": context_rules + "\n\n" + new_document + "\n\nLakukan validasi sekarang."
        }
    ],
    "format": schema,
    "options": {"temperature": 0}
}

response = requests.post(url, json=payload)
result = response.json()

parsed = json.loads(result["message"]["content"])

print(json.dumps(parsed, indent=2))

{
  "complete": [],
  "incomplete": {
    "analisa_aturan_bak": [
      "Suhu: 39.1 > 38.5 (OK)",
      "Nadi: 110 > 90 (OK)",
      "RR: 24 > 20 (OK)",
      "Leukosit: 18.000 abnormal (OK)",
      "Kultur darah: positif (OK)"
    ],
    "analisa_aturan_klinis": [
      "Suhu: 39.1 > 38.5 (OK)",
      "Nadi: 110 > 90 (OK)",
      "RR: 24 > 20 (OK)"
    ],
    "analisa_permenkes": [
      "Antibiotik: IV (OK)"
    ],
    "analisa_aturan_coding_medis": [
      "ICD-10: A40.9 - Septikemia tidak spesifik (OK)"
    ]
  },
  "improvement_suggestions": {
    "analisa_aturan_bak": [],
    "analisa_aturan_klinis": [
      "Suhu: 39.1 > 38.5 (OK)",
      "Nadi: 110 > 90 (OK)",
      "RR: 24 > 20 (OK)"
    ],
    "analisa_permenkes": [
      "Antibiotik: IV (OK)"
    ],
    "analisa_aturan_coding_medis": [
      "ICD-10: A40.9 - Septikemia tidak spesifik (OK)"
    ]
  }
}

In [9]:
parsed

{'complete': [],
 'incomplete': {'analisa_aturan_bak': ['Suhu: 39.1 > 38.5 (OK)',
   'Nadi: 110 > 90 (OK)',
   'RR: 24 > 20 (OK)',
   'Leukosit: 18.000 abnormal (OK)',
   'Kultur darah: positif (OK)'],
  'analisa_aturan_klinis': ['Suhu: 39.1 > 38.5 (OK)',
   'Nadi: 110 > 90 (OK)',
   'RR: 24 > 20 (OK)'],
  'analisa_permenkes': ['Antibiotik: IV (OK)'],
  'analisa_aturan_coding_medis': ['ICD-10: A40.9 - Septikemia tidak spesifik (OK)']},
 'improvement_suggestions': {'analisa_aturan_bak': [],
  'analisa_aturan_klinis': ['Suhu: 39.1 > 38.5 (OK)',
   'Nadi: 110 > 90 (OK)',
   'RR: 24 > 20 (OK)'],
  'analisa_permenkes': ['Antibiotik: IV (OK)'],
  'analisa_aturan_coding_medis': ['ICD-10: A40.9 - Septikemia tidak spesifik (OK)']}}

In [21]:
import requests
import json

url = "https://ai-api.paperlesshospital.id/api/chat"

schema = {
    "type": "object",
    "properties": {
        "complete": {
            "type": "array",
            "items": {"type": "string"}
        },
        "incomplete": {
            "type": "object",
            "properties": {
                "analisa_aturan_bak": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_klinis": {"type": "array", "items": {"type": "string"}},
                "analisa_permenkes": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_coding_medis": {"type": "array", "items": {"type": "string"}}
            },
            "required": [
                "analisa_aturan_bak",
                "analisa_aturan_klinis",
                "analisa_permenkes",
                "analisa_aturan_coding_medis"
            ]
        },
        "improvement_suggestions": {
            "type": "object",
            "properties": {
                "analisa_aturan_bak": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_klinis": {"type": "array", "items": {"type": "string"}},
                "analisa_permenkes": {"type": "array", "items": {"type": "string"}},
                "analisa_aturan_coding_medis": {"type": "array", "items": {"type": "string"}}
            },
            "required": [
                "analisa_aturan_bak",
                "analisa_aturan_klinis",
                "analisa_permenkes",
                "analisa_aturan_coding_medis"
            ]
        }
    },
    "required": ["complete", "incomplete", "improvement_suggestions"]
}

context_rules = """
### ATURAN SEPSIS ###
1. Minimal 2 kriteria SIRS:
   - Suhu >38.5 atau <36
   - Nadi >90
   - RR >20
2. Harus ada bukti laboratorium (Leukosit abnormal atau kultur positif)
3. Harus diberikan antibiotik IV
"""

# new_document = """
# ### DOKUMEN KLAIM BARU ###
# Diagnosis: Septikemia
# Suhu: 39.1
# Nadi: 110
# RR: 24
# Leukosit: 18.000
# Kultur darah: positif
# Antibiotik: IV
# """

new_document = """
Diagnosis: Septikemia
Suhu: 37.5
Nadi: 85
RR: 18
Leukosit: normal
Kultur darah: tidak ada
Antibiotik: oral
"""

instruction = f"""
Anda adalah validator klaim BPJS.

ATURAN PENGISIAN:

1. Field "complete" harus berisi indikator detail yang terpenuhi,
   bukan nama aturan umum.
   Contoh yang benar:
   - "Suhu 39.1 >38.5"
   - "Nadi 110 >90"
   - "Kultur darah positif"

2. Jika semua aturan terpenuhi:
   - Semua field dalam "incomplete" harus kosong []
   - Semua field dalam "improvement_suggestions" harus kosong []

3. Jika ada yang tidak terpenuhi:
   - Hanya tuliskan yang tidak terpenuhi dalam field incomplete
   - Jangan menuliskan ulang yang sudah lengkap

   
DEFINISI FIELD:

1. Field "complete":
   HANYA berisi indikator yang MEMENUHI aturan.
   Jangan masukkan indikator yang gagal.

2. Field "incomplete":
   HANYA berisi indikator yang TIDAK MEMENUHI aturan.

3. Jika suatu indikator tidak memenuhi threshold,
   maka indikator tersebut TIDAK BOLEH dimasukkan ke dalam "complete".

Contoh:
Jika Suhu 37.5 (tidak memenuhi >38.5),
maka jangan tulis "Suhu 37.5" di field complete.


Berikut konteks referensi dokumen (Gunakan ini sebagai basis pengetahuan atau aturan Anda):
{context_rules}
"""

payload = {
    "model": "qwen2.5:7b-instruct",
    "stream": False,
    "messages": [
        {
  "role": "system",
  "content": instruction
        },
        {
            "role": "user",
            "content": new_document + "\n\nLakukan validasi sekarang."
        }
    ],
    "format": schema,
    "options": {"temperature": 0}
}

response = requests.post(url, json=payload)
result = response.json()

parsed = json.loads(result["message"]["content"])

print(json.dumps(parsed, indent=2))

{
  "complete": [],
  "incomplete": {
    "analisa_aturan_bak": [
      "Kultur darah: tidak ada"
    ],
    "analisa_aturan_klinis": [
      "Suhu: 37.5",
      "Nadi: 85",
      "RR: 18"
    ],
    "analisa_permenkes": [
      "Leukosit normal"
    ],
    "analisa_aturan_coding_medis": []
  },
  "improvement_suggestions": {
    "analisa_aturan_bak": [],
    "analisa_aturan_klinis": [],
    "analisa_permenkes": [
      "Leukosit normal, perlu diperiksa kembali"
    ],
    "analisa_aturan_coding_medis": []
  }
}

In [7]:
parsed

{'complete': ['Suhu >36',
  'Nadi >90',
  'RR >20',
  'Leukosit abnormal',
  'Kultur positif',
  'Antibiotik IV'],
 'incomplete': {'analisa_aturan_bak': ['Minimal 2 kriteria SIRS dipenuhi (Suhu: 39.1 >38.5, Nadi: 110 >90, RR: 24 >20)',
   'Bukti laboratorium tersedia (Leukosit abnormal: 18.000, Kultur darah positif)',
   'Antibiotik IV telah diberikan'],
  'analisa_aturan_klinis': ['Diagnosis: Septikemia sesuai dengan gejala dan tanda-tanda SIRS yang dipenuhi',
   'Tidak ada kriteria SIRS yang tidak dipenuhi, semua kriteria terpenuhi'],
  'analisa_permenkes': ['Semua kriteria untuk klaim sepsis sesuai dengan aturan Permendik康健部 (dalam konteks ini, mungkin maksudnya adalah Permenkes atau peraturan kesehatan yang berlaku)'],
  'analisa_aturan_coding_medis': ['Diagnosis dan tanda-tanda SIRS sesuai dengan ICD-10 (Tidak ada pengecekan spesifik ICD-10 dalam konteks ini, namun diagnosis sepsis umumnya mencakup kriteria SIRS)']},
 'improvement_suggestions': {'analisa_aturan_bak': ['Semua kriteria untuk klaim sepsis telah dipenuhi.'],
  'analisa_aturan_klinis': ['Diagnosis dan tanda-tanda SIRS yang diberikan sesuai dengan aturan yang berlaku.'],
  'analisa_permenkes': ['Semua kriteria untuk klaim sepsis telah dipenuhi, sehingga klaim dapat disetujui.'],
  'analisa_aturan_coding_medis': ['Diagnosis dan tanda-tanda SIRS sesuai dengan standar medis yang berlaku.']}}

In [55]:
url = "http://localhost:8002/checking-klaim-bpjs/v1/check-kelengkapan-berkas-baru"
text = """

RS PAPERLESS HOSPITAL
No. SEP: 2209R0010125V012762
Tanggal Pelayanan: 13/01/2025 (Estimasi berdasarkan No. Registrasi)
Diagnosa Utama: A01.0 (Typhoid fever)
Diagnosa Sekunder: Z09.8 (Follow-up examination after other treatment for other conditions)
Prosedur: -
Biaya: (Tidak tertera di data mentah, namun biasanya masuk kategori Rawat Jalan Tingkat Lanjut)

RINGKASAN KLINIS:
Keluhan Utama: Kontrol post cek laboratorium.
Riwayat Penyakit Sekarang: Pasien datang untuk kontrol hasil laboratorium. Saat ini keluhan demam tidak ada. Keluhan mual dan muntah disangkal.
Riwayat Penyakit Dahulu: -

PEMERIKSAAN FISIK:
    Kesadaran: Compos Mentis (GCS E4V5M6)

    Tanda Vital:
        - Tekanan Darah: 133/86 mmHg
        - Nadi: 74 x/menit (reguler, kuat angkat)
        - Frekuensi Nafas: 18 x/menit
        - Suhu: 36.4 °C
        - SPO2: 99%
        - Mata: Anemis (-/-), Ikterik (-/-)
        - Mulut: Leukoplakia (+)
        - Leher: Pembesaran KGB (-)

    Thorax:
        - Cor: S1 S2 tunggal, murmur (-)
        - Pulmo: Vesikuler (+/+/+), Rhonki (-/-/-), Wheezing (-/-/-)

    Abdomen: Distensi (-), Bising Usus (+) Normal, Soepel, Nyeri tekan (-), Organomegali (-)
    Ekstremitas: Akral hangat (+/+), Edema (-/-), Tremor (-/-)

    HASIL LABORATORIUM (09-01-2025 14:02:39):
        - Malaria (Rapid): Negatif
        - Anti Salmonella Typhi IgM: Positif (Score 6) (Referensi: Negatif: Score 2-3, Positif Lemah: Score 4, Positif Kuat: Score 6-10)

    TERAPI / OBAT:
    - Levofloxacin 500 mg (3x500mg IO)
    - Asam Mefenamat
"""

payload = {
    "result_checkup": text
}


response = requests.post(url, json=payload)
result = response.json()
print(json.dumps(result, indent=2))

{
  "code": 200,
  "message": "OK",
  "data": {
    "result": {
      "complete": [
        "ringkasan_konten",
        "identifikasi_risiko",
        "rekomendasi"
      ],
      "incomplete": {
        "analisa_aturan_bak": [],
        "analisa_aturan_klinis": [],
        "analisa_permenkes": [],
        "analisa_aturan_coding_medis": []
      },
      "improvement_suggestions": {
        "analisa_aturan_bak": [],
        "analisa_aturan_klinis": [],
        "analisa_permenkes": [],
        "analisa_aturan_coding_medis": []
      }
    },
    "debug": {
      "prompt": "\nBerikut document text yang harus anda check:\n--- REFERENCE DOCUMENTS START ---\n\n\nRS PAPERLESS HOSPITAL\nNo. SEP: 2209R0010125V012762\nTanggal Pelayanan: 13/01/2025 (Estimasi berdasarkan No. Registrasi)\nDiagnosa Utama: A01.0 (Typhoid fever)\nDiagnosa Sekunder: Z09.8 (Follow-up examination after other treatment for other conditions)\nProsedur: -\nBiaya: (Tidak tertera di data mentah, namun biasanya masuk kategori Rawat Jalan Tingkat Lanjut)\n\nRINGKASAN KLINIS:\nKeluhan Utama: Kontrol post cek laboratorium.\nRiwayat Penyakit Sekarang: Pasien datang untuk kontrol hasil laboratorium. Saat ini keluhan demam tidak ada. Keluhan mual dan muntah disangkal.\nRiwayat Penyakit Dahulu: -\n\nPEMERIKSAAN FISIK:\n    Kesadaran: Compos Mentis (GCS E4V5M6)\n\n    Tanda Vital:\n        - Tekanan Darah: 133/86 mmHg\n        - Nadi: 74 x/menit (reguler, kuat angkat)\n        - Frekuensi Nafas: 18 x/menit\n        - Suhu: 36.4 \u00b0C\n        - SPO2: 99%\n        - Mata: Anemis (-/-), Ikterik (-/-)\n        - Mulut: Leukoplakia (+)\n        - Leher: Pembesaran KGB (-)\n\n    Thorax:\n        - Cor: S1 S2 tunggal, murmur (-)\n        - Pulmo: Vesikuler (+/+/+), Rhonki (-/-/-), Wheezing (-/-/-)\n\n    Abdomen: Distensi (-), Bising Usus (+) Normal, Soepel, Nyeri tekan (-), Organomegali (-)\n    Ekstremitas: Akral hangat (+/+), Edema (-/-), Tremor (-/-)\n\n    HASIL LABORATORIUM (09-01-2025 14:02:39):\n        - Malaria (Rapid): Negatif\n        - Anti Salmonella Typhi IgM: Positif (Score 6) (Referensi: Negatif: Score 2-3, Positif Lemah: Score 4, Positif Kuat: Score 6-10)\n\n    TERAPI / OBAT:\n    - Levofloxacin 500 mg (3x500mg IO)\n    - Asam Mefenamat\n\n--- REFERENCE DOCUMENTS END ---\n\nSekarang anda dapat memverifikasi administrasi klaim BPJS Kesehatan. Berdasarkan dokumen yang diberikan, jawab pertanyaan pengguna dan ikuti instruksinya. Buat analisis yang terstruktur, akurat dan konsisten, berikan jawaban yang tepat dan rujuk dokumen jika perlu.\n",
      "system_instruction": "\nAnda adalah asisten AI yang ahli dalam memverifikasi administrasi klaim BPJS Kesehatan. Tugas Anda adalah menganalisis dokumen klaim yang telah diekstrak menjadi teks, memeriksa setiap halaman, dan memastikan validitasnya.\n\n---\n\n### **Tugas Utama**\n\n1.  **Analisis Dokumen:**\n    * Membaca dan memverifikasi setiap halaman dokumen klaim yang telah diekstrak ke dalam teks.\n    * **Periksa Judul Halaman:** Verifikasi judul atau header setiap halaman untuk memastikan kelengkapan dokumen (misalnya, SEP, Resume Medis, Laporan Operasi, dll.). Jika sebuah halaman kosong atau tidak memiliki informasi yang relevan, tandai sebagai **berkas tidak lengkap**.\n2.  **Verifikasi Prosedur & Medis:**\n    * Periksa apakah prosedur dan pemeriksaan medis yang diajukan sesuai dengan ketentuan BPJS Kesehatan.\n    * Identifikasi dan analisis ketidaksesuaian dalam klaim, baik dari segi dokumen, prosedur, maupun cakupan layanan.\n3.  **Pengkodean & Rekomendasi:**\n    * Analisis diagnosis utama dan tindakan untuk mengidentifikasi **kode ICD-10** dan **ICD-9**. Jika kode tidak ditemukan, berikan rekomendasi pengkodean yang tepat.\n    * Berikan catatan atau rekomendasi perbaikan yang diperlukan agar klaim sesuai.\n    * Jika kode ICD tertentu memerlukan dokumen penunjang, sebutkan dokumen spesifik yang harus dilengkapi (misalnya, hasil laboratorium, radiologi, laporan operasi).\n4.  **Analisis Mendalam & Kepatuhan Regulasi:**\n    * **Lama Rawat Inap:** Bandingkan lama rawat inap dengan diagnosis dan prosedur yang diklaim. Nilai apakah durasi tersebut wajar dan sesuai dengan standar klinis.\n    * **Tingkat Layanan:** Periksa apakah pasien dirawat di tingkat layanan yang lebih tinggi dari yang seharusnya.\n    * **Justifikasi Medis:** Periksa perpanjangan rawat inap yang tidak memiliki justifikasi medis jelas dalam rekam medis.\n    * **Kepatuhan Pengkodean:** Pastikan pengkodean diagnosis dan prosedur sesuai dengan pedoman **ICD-10** dan **ICD-9-CM versi terbaru** yang berlaku di BPJS Kesehatan.\n    * **Pedoman Khusus:** Verifikasi kepatuhan terhadap Berita Acara Kesepakatan (**BAK**) atau pedoman khusus dari BPJS Kesehatan yang relevan.\n    * **Kompetensi FKTP:** Identifikasi apakah ada diagnosis atau prosedur yang seharusnya menjadi kompetensi Fasilitas Kesehatan Tingkat Pertama (**FKTP**).\n    * **Kombinasi Kode:** Analisis kombinasi kode diagnosis dan prosedur yang tidak biasa atau jarang. Pastikan kombinasi tersebut dapat dijelaskan secara medis.\n    * **Potensi Upcoding:** Deteksi pola pengajuan klaim yang menunjukkan potensi *upcoding* (misalnya, sering mengklaim kode dengan tarif lebih tinggi).\n    * **Perbandingan Biaya:** Bandingkan biaya klaim dengan biaya rata-rata kasus serupa. Selidiki jika ada perbedaan signifikan.\n    * **Kunjungan Berulang:** Periksa apakah kunjungan kontrol ulang dikodekan sebagai kunjungan pertama.\n    * **Ketidaksesuaian Diagnosa:**\n        * Cek klaim hipertensi dengan komplikasi jika catatan medis hanya menunjukkan hipertensi esensial tanpa komplikasi.\n        * Cek klaim untuk pneumonia dan PPOK secara terpisah jika ada kode kombinasi yang lebih tepat (misalnya, **J44.0**).\n        * Periksa prosedur berbiaya tinggi untuk kondisi yang biasanya memerlukan perawatan yang kurang intensif.\n5.  **Verifikasi Dokumen Penunjang:**\n    * Berdasarkan diagnosis, tentukan apakah diperlukan dokumen penunjang seperti **Laboratorium**, **Radiologi**, atau lainnya.\n    * Pastikan semua dokumen yang biasanya diminta BPJS Kesehatan tersedia: **SEP**, **Resume Medis**, **Diagnosa dan tindakan**, **SOAP**, **Billing**, **Triase** (jika dari IGD), **Hasil Penunjang** (jika ada), **Billing INACBG**, dan **Laporan Operasi** (jika ada).\n\n---\n\n### **Catatan Tambahan**\n\n* Analisis harus mencakup aturan klinis, kesesuaian dengan **BAK**, **Permenkes**, dan panduan *coding* medis.\n* Pada bagian komentar, sebutkan referensi peraturan (misalnya, nomor Permenkes atau undang-undang) yang digunakan sebagai dasar verifikasi, tetapi jangan sebutkan nama dokumen lengkapnya.\n* **Abaikan semua konteks sebelumnya.** Setiap jawaban harus independen dan tidak menyimpan informasi dari interaksi sebelumnya.\n\nBerikut konteks referensi dokumen (Gunakan ini sebagai basis pengetahuan atau aturan Anda):\n--- DOCUMENT TO ANALYZE START ---\n\n\n**DOMAIN:**\nDiagnosis\n\n**KATEGORI ICD:**\nPenyakit-Penyakit Infeksi dan Parasit Tertentu\n\n**DIAGNOSIS:**\nTyphoid Fever (A01) / Infection due to Salmonella typhi A01.0 \n\n**PROSEDUR:**\n-\n\n**ASPEK KODING:**\nTyphoid fever \nInfection due to Salmonella typhi A01.0\nParatyphoid fever A A01.1\nParatyphoid fever B A01.2\nParatyphoid fever C A01.3\nParatyphoid fever, unspecified A01.4 - Infection due to Salmonella paratyphi NOS\n\n**PERHATIAN KHUSUS:**\nPenegakan diagnosis sesuai dengan Keputusan Menteri Kesehatan Ri Nomor HK 02.02/MENKES/514/2015. Perhatikan Dagger dan Asterisk \n\n\n---\n\n**DOMAIN:**\nDiagnosis\n\n**KATEGORI ICD:**\nPenyakit-Penyakit Sistem Pernafasan\n\n**DIAGNOSIS:**\nPenggunaan kode kombinasi untuk Pneumonia, unspecified dengan Typhoid fever menjadi Localized salmonella infections (A02.2)\n\n**PROSEDUR:**\n-\n\n**ASPEK KODING:**\nICD 10 2010 Volume 3\nTyphoid (abortive) (ambulant) (any site)\n(fever) (hemorrhagic) (infection)\n(intermittent) (malignant) (rheumatic)\nA01.0\n- inoculation reaction \u2014 see\nComplications, vaccination\n- pneumonia A01.0\u2020 J17.0*\nSesuai dengan intruksi pada volume I sub bab pneumonia in diseases classified elsewhere (J17) yang menyatakan penggunaan pneumonia (due to)(in) \u00b7 typhoid fever mengarah kode dagger (A01.0\u2020) dan asterisk (J17.0*). Bukan kode kombinasi.\n\n**PERHATIAN KHUSUS:**\nDiagnosa demam tifoid dan pneumonia dikode dengan dagger asterisk dengan A01.0+ dan J17.0*\nPenegakan diagnosa pneumonia lihat lampiran Bab Medis poin no. 3\nPenggunaan kode A01.0 atau A02.2 ditentukan berdasarkan jenis kuman, pada kondisi adanya pneumonia, menggunakan kode asterisk J17.0*\n\n\n---\n\n**DOMAIN:**\nDiagnosis\n\n**KATEGORI ICD:**\nPenyakit-Penyakit Infeksi dan Parasit Tertentu\n\n**DIAGNOSIS:**\nPenggunaan kode kombinasi untuk Typhoid fever (A01) dengan Dianhoea and gastroententis of presumed infectious engin menjadi Salmonella enteritis \n\n**PROSEDUR:**\n-\n\n**ASPEK KODING:**\nSesuai dengan instruksi excludes pada volume I sub bab other gastroententis and colitis of infectious and unspecified onigin fever (A09) yang menyatakan gastroententis and colitis due to bacterial, protozoal, viral and other specified infectious agents mengarah pada kode spesifik sesuai dengan organismenya (A00-A08) Sehingga kode A09 seharusnya tidak dikoding lagi apabila sudah ada typhoid fever (A01.0) yang tegak secara medis. Tidak ada instruksi khusus untuk menggabungkan antara A01.0 dengan A09 menjadi salmonella, enteritis (A02.0) baik dari volume 1 maupun III \n\n**PERHATIAN KHUSUS:**\n-\n\n\n---\n\n**DOMAIN:**\nDiagnosis\n\n**KATEGORI ICD:**\nGejala, Tanda, dan Hasil Abnormal Klinis Dan Laboratorium, Tidak Diklasifikasikan di Tempat Lain\n\n**DIAGNOSIS:**\nFever (R50.9)\n\n**PROSEDUR:**\n-\n\n**ASPEK KODING:**\nTermasuk Didalamnya: Hyperpyrexia NOS, Pyrexia NOS. Kriteria eksklusi Sub Bab: demam saat persalinan (O75.2), newborn (P81.9), Puerperal pyrexia NOS (O86.4).\n\n**PERHATIAN KHUSUS:**\nKonfirmasi penyebab demam yang spesifik sesuai klinis dan pemeriksaan penunjang, tata laksana dan pemeriksaan penunjang. Jika merupakan bagian tanda dan gejala dari suatu penyakit, maka tidak dapat dikoding terpisah.\n\n\n---\n\n**DOMAIN:**\nDiagnosis\n\n**KATEGORI ICD:**\nPenyakit-Penyakit Infeksi dan Parasit Tertentu\n\n**DIAGNOSIS:**\nTuberculous pleurisy, conf bacteriologically/his'y (A15.6) \n\n**PROSEDUR:**\n-\n\n**ASPEK KODING:**\nA15.6 Tuberculous pleurisy, confirmed bacteriologically and histologically. Tuberculosis of pleura. Tuberculosis empyema comfirmed bacteriologically and histologically. Excludes in primary respiratory tuberculosis, confirmed bacteriologically and histologically (A15.7). \n\n**PERHATIAN KHUSUS:**\nPerhatikan pada sub bab (A15-A19) Includes infections due to Mycobacterium tuberculosis and Myocobacterium bovis. Excludes congenital tuberculosis (P37.0), human immunodeficiency HIV disease resulting in tuberculosis (B20.0), pneumoconiosis associated with tuberculosis (J65), sequelae of tuberculosis (B90.-), silicotuberculosis (J65). \n\n\n---\n\n\n**DIAGNOSIS:**\nRespiratory Failure (Gagal Nafas)\n\n**PROSEDUR:**\n-\n\n**ASPEK MEDIS:**\nKriteria gagal napas akut (acute respiratory failure) (J96.0) apabila memenuhi salah satu kriteria berikut ini:\n1. Hasil pemeriksaan analisis gas darah menunjukkan pO2 < 60 mmHg dan/atau SaO2 < 91%\n2. Hasil pemeriksaan pulse oksimetri menunjukkan SpO2 < 91%\n3. Hasil pemeriksaan analisis gas darah menunjukkan pO2 / FiO2 (P/F) ratio < 300\n4. Hasil pemeriksaan analisis gas darah menunjukkan pCO2 > 50 mmHg dengan pH < 7,35\n5. Hasil pemeriksaan analisis gas darah menunjukkan peningkatan pCO2 \u2265 10 mmHg dari nilai dasar (bila diketahui hasil analisis gas darah sebelumnya)\nKriteria gagal napas kronik (chronic respiratory failure) (J96.1) apabila memenuhi seluruh kriteria berikut ini:\na. peningkatan pCO2 > 50 mmHg\nb. peningkatan bikarbonat (HCO3) > 24 mmHg\nc. pH normal (7,35 \u2013 7,45)\nd. pO2 < 60 mmHg dan / atau SaO2 < 91%\nKriteria gagal napas akut pada gagal napas kronik (acute on chronic respiratory failure) adalah pasien dengan riwayat gagal napas kronik apabila memenuhi salah satu kriteria berikut ini:\n1. Perburukan gejala klinis berupa penurunan kesadaran atau sesak napas atau gasping\n2. Hasil pemeriksaan analisis gas darah atau pulse oksimetri menunjukkan:\na. Hasil pemeriksaan gas darah yang menunjukkan penurunan pO2 < 60 mmHg dan/ atau penurunan SaO2 < 91%\nb. Hasil pemeriksaan pulse oksimetri menunjukkan penurunan SpO2 < 91%\n3. Hasil pemeriksaan analisis gas darah menunjukkan peningkatan pCO2 > 50 mmHg dan pH < 7,35\nTatalaksana salah satu dibawah ini :\n1. Terapi oksigen dengan :\n- Low flow: nasal kanul, masker simple, rebreathing mask, non-rebreathing mask\n- High flow: venturi mask, high flow nasal kanul\n2. Ventilasi non invasif: CPAP, BiPAP\n3. Ventilasi invasive (ventilator)\n\n**PERHATIAN KHUSUS:**\n-\n\n\n---\n\n**DOMAIN:**\nDiagnosis\n\n**KATEGORI ICD:**\nPenyakit-Penyakit Infeksi dan Parasit Tertentu\n\n**DIAGNOSIS:**\nTyphoid pada kehamilan (dirawat oleh dokter spesialis dalam) \n\n**PROSEDUR:**\n-\n\n**ASPEK KODING:**\nJika tidak ada diagnosis lainnya, maka pengkodaan untuk kasus tifoid pada kehamilan menggunakan kode 098 8 sebagai diagnosis utama dan kode A01.0 sebagai diagnosis sekunder \n\n**PERHATIAN KHUSUS:**\nSesuai PMK No.76 Tahun 2016. Jika dalam ICD-10 terdapat catatan seperti Lise additional code, if desired, to identify specified condition, maka kode tersebut dapat digunakan sesuai dengan kondisi pasien. \n\n--- DOCUMENT TO ANALYZE END ---\n"
    }
  }
}